kind: Service
apiVersion: v1
metadata:
  name: spring-dummy-service
spec:
  selector:
    app: spring-dummy-service
  ports:
    - protocol: TCP
      port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-dummy-service
spec:
  selector:
    matchLabels:
      app: spring-dummy-service
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-dummy-service
    spec:
      containers:
        - name: spring-dummy-service
          image: localhost:5000/spring-dummy-service
          ports:
            - containerPort: 8080
