server.port: 8080
spring:
  application:
    name: gateway-service

# Spring Boot Actuator
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
