apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
#  # default backend
#  backend:
#    serviceName: gateway-service
#    servicePort: 8080
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: gateway-service
              servicePort: 8080
